/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRetentionRouteImport } from './routes/privacy.retention'
import { Route as PrivacyExportRouteImport } from './routes/privacy.export'
import { Route as PrivacyDeleteRouteImport } from './routes/privacy.delete'
import { Route as OrdersBudgetRouteImport } from './routes/orders_.budget'
import { Route as ApprovalsHistoryRouteImport } from './routes/approvals.history'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRetentionRoute = PrivacyRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => PrivacyRoute,
} as any)
const PrivacyExportRoute = PrivacyExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => PrivacyRoute,
} as any)
const PrivacyDeleteRoute = PrivacyDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => PrivacyRoute,
} as any)
const OrdersBudgetRoute = OrdersBudgetRouteImport.update({
  id: '/orders_/budget',
  path: '/orders/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsHistoryRoute = ApprovalsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ApprovalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/chat': typeof ChatRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/approvals/history': typeof ApprovalsHistoryRoute
  '/orders/budget': typeof OrdersBudgetRoute
  '/privacy/delete': typeof PrivacyDeleteRoute
  '/privacy/export': typeof PrivacyExportRoute
  '/privacy/retention': typeof PrivacyRetentionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/chat': typeof ChatRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/approvals/history': typeof ApprovalsHistoryRoute
  '/orders/budget': typeof OrdersBudgetRoute
  '/privacy/delete': typeof PrivacyDeleteRoute
  '/privacy/export': typeof PrivacyExportRoute
  '/privacy/retention': typeof PrivacyRetentionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/chat': typeof ChatRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/approvals/history': typeof ApprovalsHistoryRoute
  '/orders_/budget': typeof OrdersBudgetRoute
  '/privacy/delete': typeof PrivacyDeleteRoute
  '/privacy/export': typeof PrivacyExportRoute
  '/privacy/retention': typeof PrivacyRetentionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/chat'
    | '/orders'
    | '/privacy'
    | '/approvals/history'
    | '/orders/budget'
    | '/privacy/delete'
    | '/privacy/export'
    | '/privacy/retention'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/chat'
    | '/orders'
    | '/privacy'
    | '/approvals/history'
    | '/orders/budget'
    | '/privacy/delete'
    | '/privacy/export'
    | '/privacy/retention'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/chat'
    | '/orders'
    | '/privacy'
    | '/approvals/history'
    | '/orders_/budget'
    | '/privacy/delete'
    | '/privacy/export'
    | '/privacy/retention'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRouteWithChildren
  ChatRoute: typeof ChatRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRouteWithChildren
  OrdersBudgetRoute: typeof OrdersBudgetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/retention': {
      id: '/privacy/retention'
      path: '/retention'
      fullPath: '/privacy/retention'
      preLoaderRoute: typeof PrivacyRetentionRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/privacy/export': {
      id: '/privacy/export'
      path: '/export'
      fullPath: '/privacy/export'
      preLoaderRoute: typeof PrivacyExportRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/privacy/delete': {
      id: '/privacy/delete'
      path: '/delete'
      fullPath: '/privacy/delete'
      preLoaderRoute: typeof PrivacyDeleteRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/orders_/budget': {
      id: '/orders_/budget'
      path: '/orders/budget'
      fullPath: '/orders/budget'
      preLoaderRoute: typeof OrdersBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/history': {
      id: '/approvals/history'
      path: '/history'
      fullPath: '/approvals/history'
      preLoaderRoute: typeof ApprovalsHistoryRouteImport
      parentRoute: typeof ApprovalsRoute
    }
  }
}

interface ApprovalsRouteChildren {
  ApprovalsHistoryRoute: typeof ApprovalsHistoryRoute
}

const ApprovalsRouteChildren: ApprovalsRouteChildren = {
  ApprovalsHistoryRoute: ApprovalsHistoryRoute,
}

const ApprovalsRouteWithChildren = ApprovalsRoute._addFileChildren(
  ApprovalsRouteChildren,
)

interface PrivacyRouteChildren {
  PrivacyDeleteRoute: typeof PrivacyDeleteRoute
  PrivacyExportRoute: typeof PrivacyExportRoute
  PrivacyRetentionRoute: typeof PrivacyRetentionRoute
}

const PrivacyRouteChildren: PrivacyRouteChildren = {
  PrivacyDeleteRoute: PrivacyDeleteRoute,
  PrivacyExportRoute: PrivacyExportRoute,
  PrivacyRetentionRoute: PrivacyRetentionRoute,
}

const PrivacyRouteWithChildren =
  PrivacyRoute._addFileChildren(PrivacyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRouteWithChildren,
  ChatRoute: ChatRoute,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRouteWithChildren,
  OrdersBudgetRoute: OrdersBudgetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
